#! /usr/bin/perl -lw
# (c) 2015 D.Bereziat
# Convert sng file to tex. Sng is my own format, quicker
# to type than chord in my opinion.

use strict;

my $numsong = 1;

# LaTeX header
my ($title,$authors,$titlepage,$index);

for (@ARGV) {
  do {
    print STDERR "Usage is: sng2tex [-t][-i] FILE FILE ...";
    exit 1;
  } if /^-h/;
  $titlepage = 1 if /^-t$/;
  $index = 1 if /^-i$/;
}

# FIXME: 
print "\\documentclass[twoside]{article}";
print "\\usepackage{fullpage,hyperref}";
print "\\usepackage[chorded]{songs}";
print "\\usepackage[utf8]{inputenc}";
print "\\noversenumbers";
print "\\songcolumns{1}";
print "\\renewcommand{\\lyricfont}{\\sffamily\\Large}";
print "\\renewcommand{\\printchord}[1]{\\rmfamily\\bf#1}";

print "\\begin{document}";
print "\\title{The Famous Boby Boeuf Songbook}";
# print "\\date{March 2015}";
print "\\maketitle" if $titlepage;
print "\\input{index}" if $index;
print "\\begin{songs}{}";

# Index of songs
open IND, ">index.tex";
print IND "\\begin{center} \\huge \\bf Index of songs \\end{center}\n\\begin{enumerate}";

for my $file (@ARGV) {
  next if $file =~ /^-/;

  open (F, "<$file") ;

  do { $_=<F>} while (/^%%/) ;
  $title = $_;
  chomp $title;
  do { $_=<F>} while (/^%%/) ;
  $authors = $_;
  chomp $authors;

  print "\\beginsong{$title}[by={$authors}]\\label{song$numsong}";
  # index song:
  print IND "\\item [] \\large $title ($authors) \\hfill page \\pageref{song$numsong}";

  $numsong ++;

  # read chords definition
  while ( <F>) {
    chomp;
    # Skips comments
    next if /^%%/;
    next if /^#/;
    
    # Chord definitions
    if (/^%chord +(\S+) +(\S+)/) {
      my $name = $1;
      my $def = $2;
      $name =~ s/b/\&/;
      print "\\gtab{$name}{$def}";
      next;
    }
    last;
  }

  print "\\beginverse";

  while( <F>) {
    chomp;
    # Comments
    next if /^%%/;
    next if /^#/;

    # Annotations
    do { print "\\vspace*{.3cm}\\textnote{$1}"; next} if /^%\s+(.*)/ ;

    # LaTeX does not like that character
    s/_/ /g;

    # Protect & : FIXME ne marche pas !!!!!
    s/&/\\\&/g;

    # bloc between chords or between last chord and end of ligne
    s/\]([^\s[][^\[]*)/\]\{$1\}/g;

    # remove blank blocs
    s/\{\s*\}//g;

    # Prefix chords
    s/\[/\\[/g;

    # Bemol in chords (convert b to &)
    #   while (s/(\[[^\]])b(?=.*\])/$1\&/) {};
    s/(\[[^\]])b(?=.*\])/$1\&/g;

    # Measure bars
    s/\|/\$\\mid\$/g;
#    while (s/(\[[^\]])|(?=.*\])/$1\$\\mid\$/) {};

    # capture words group / isolated letter(s) with _ marker
    #    while (s/\](([^_\[]+)_)/\]\{$2\}/) {};

    print ;
  }
  close F;

  print "\\endverse";
  print "\\endsong";
  print "%%%%%%%%%%%%%%%"
}

print "\\end{songs}";
print "\\end{document}";

print IND "\\end{enumerate}";
close IND;
