#! /usr/bin/perl -lw
# (c) 2015 D.Bereziat

use strict;

my $numsong = 1;

# Entête LaTeX
my ($title,$authors,$cr);
print "\\documentclass{article}";
print "\\usepackage{fullpage}";
print "\\usepackage[chorded]{songs}";
print "\\usepackage[utf8]{inputenc}";
print "\\noversenumbers";
print "\\begin{document}";
print "\\title{The Famous Boby Boeuf Songbook}";
print "\\date{May 2015}";
print "\\maketitle";
print "\\include{index}";
print "\\begin{songs}{}";

# Index of songs
open IND, ">index.tex";
print IND "\\begin{center} \\huge \\bf Index of songs \\end{center}\n\\begin{enumerate}";

for my $file (@ARGV) {
  open (F, "<$file") ;

  do { $_=<F>} while (/^%%/) ;
  $title = $_;
  chomp $title;
  do { $_=<F>} while (/^%%/) ;
  $authors = $_;
  chomp $authors;

  print "\\beginsong{$title}[by={$authors}]\\label{song$numsong}";

  # index song:
  print IND "\\item [] \\Large $title \\hfill page \\pageref{song$numsong}";

  $numsong ++;

  # read chords definition
  while ( <F>) {
    chomp;
    # Skips comments
    next if /^%%/;
    # Chord definitions
    do { print "\\gtab{$1}{$2}"; next} if /^%chord +(\S+) +(\S+)/;
    last;
  }

  print "\\beginverse";

  while( <F>) {
    chomp;
    # Comments
    next if /^%%/;

    # Annotations
    do { print "\\vspace*{.3cm}\\textnote{$1}"; next} if /^%\s+(.*)/ ;

    # Chords
    s/\[/\\[/g;

    # Bemol in chords (convert b to &)
    while (s/(\[[^\]])b(?=.*\])/$1\&/) {};

    # capture words group / isolated letter(s) with _ marker
    while (s/\](([^_\[]+)_)/\]\{$2\}/) {};

    print ;
  }
  close F;

  print "\\endverse";
  print "\\endsong";
  print "%%%%%%%%%%%%%%%"
}

print "\\end{songs}";
print "\\end{document}";

print IND "\\end{enumerate}";
close IND;
